let abecedario = ['c', 'b', 'a', 'z', 'y', 'm'];
// console.log(abecedario.length);
// console.log(abecedario[abecedario.length - 2]);
// console.log(abecedario.sort());
// console.log(abecedario.includes('q'));
// abecedario.push('x');
// abecedario.pop();
// abecedario.unshift('x');
// abecedario.shift();
abecedario.splice(1,2);
console.log(abecedario);
